// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: httprule/internal/test.proto

package internal

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TestMessage1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 string `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
}

func (x *TestMessage1) Reset() {
	*x = TestMessage1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_httprule_internal_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMessage1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage1) ProtoMessage() {}

func (x *TestMessage1) ProtoReflect() protoreflect.Message {
	mi := &file_httprule_internal_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage1.ProtoReflect.Descriptor instead.
func (*TestMessage1) Descriptor() ([]byte, []int) {
	return file_httprule_internal_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage1) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

type TestMessage2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1    string      `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2    int32       `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3Sub *SubMessage `protobuf:"bytes,3,opt,name=field3_sub,json=field3Sub,proto3" json:"field3_sub,omitempty"`
}

func (x *TestMessage2) Reset() {
	*x = TestMessage2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_httprule_internal_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMessage2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage2) ProtoMessage() {}

func (x *TestMessage2) ProtoReflect() protoreflect.Message {
	mi := &file_httprule_internal_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage2.ProtoReflect.Descriptor instead.
func (*TestMessage2) Descriptor() ([]byte, []int) {
	return file_httprule_internal_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestMessage2) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

func (x *TestMessage2) GetField2() int32 {
	if x != nil {
		return x.Field2
	}
	return 0
}

func (x *TestMessage2) GetField3Sub() *SubMessage {
	if x != nil {
		return x.Field3Sub
	}
	return nil
}

type SubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubField string `protobuf:"bytes,1,opt,name=sub_field,json=subField,proto3" json:"sub_field,omitempty"`
}

func (x *SubMessage) Reset() {
	*x = SubMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_httprule_internal_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMessage) ProtoMessage() {}

func (x *SubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_httprule_internal_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMessage.ProtoReflect.Descriptor instead.
func (*SubMessage) Descriptor() ([]byte, []int) {
	return file_httprule_internal_test_proto_rawDescGZIP(), []int{2}
}

func (x *SubMessage) GetSubField() string {
	if x != nil {
		return x.SubField
	}
	return ""
}

var File_httprule_internal_test_proto protoreflect.FileDescriptor

var file_httprule_internal_test_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x68, 0x74, 0x74, 0x70, 0x72, 0x75, 0x6c, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26,
	0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x22, 0x6a, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x12, 0x2a, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33,
	0x5f, 0x73, 0x75, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x75, 0x62,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x53,
	0x75, 0x62, 0x22, 0x29, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x24, 0x5a,
	0x22, 0x66, 0x6f, 0x78, 0x79, 0x67, 0x6f, 0x2e, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x67, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x72, 0x75, 0x6c, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_httprule_internal_test_proto_rawDescOnce sync.Once
	file_httprule_internal_test_proto_rawDescData = file_httprule_internal_test_proto_rawDesc
)

func file_httprule_internal_test_proto_rawDescGZIP() []byte {
	file_httprule_internal_test_proto_rawDescOnce.Do(func() {
		file_httprule_internal_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_httprule_internal_test_proto_rawDescData)
	})
	return file_httprule_internal_test_proto_rawDescData
}

var file_httprule_internal_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_httprule_internal_test_proto_goTypes = []interface{}{
	(*TestMessage1)(nil), // 0: TestMessage1
	(*TestMessage2)(nil), // 1: TestMessage2
	(*SubMessage)(nil),   // 2: SubMessage
}
var file_httprule_internal_test_proto_depIdxs = []int32{
	2, // 0: TestMessage2.field3_sub:type_name -> SubMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_httprule_internal_test_proto_init() }
func file_httprule_internal_test_proto_init() {
	if File_httprule_internal_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_httprule_internal_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMessage1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_httprule_internal_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMessage2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_httprule_internal_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_httprule_internal_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_httprule_internal_test_proto_goTypes,
		DependencyIndexes: file_httprule_internal_test_proto_depIdxs,
		MessageInfos:      file_httprule_internal_test_proto_msgTypes,
	}.Build()
	File_httprule_internal_test_proto = out.File
	file_httprule_internal_test_proto_rawDesc = nil
	file_httprule_internal_test_proto_goTypes = nil
	file_httprule_internal_test_proto_depIdxs = nil
}
